import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Map from '../components/map'
import CustHeader from '../components/header'
import CustFooter from '../components/footer'
import TextContainer from '../components/textCont'
import TextContainer2 from '../components/textCont2'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Expo Line Map by DK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/trainIcon2.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap"
          rel="stylesheet">
        </link>
      </Head>
      <main className={styles.custFont}>
        <CustHeader />
        <TextContainer2 />
        <Map />
        <TextContainer />
        <CustFooter />
      </main>
    </>
  )
}
